In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)

In [3]:
data = iris.data[["petal length (cm)", "petal width (cm)"]]
data = (data-data.mean())/data.std()
data.head()

petal length (cm)  petal width (cm)
0          -1.335752         -1.311052
1          -1.335752         -1.311052
2          -1.392399         -1.311052
3          -1.279104         -1.311052
4          -1.335752         -1.311052

In [4]:
target = iris["target"]
target.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [7]:
target.value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [471]:
target_encoded = pd.get_dummies(target, sparse=True)
target_np = target_encoded.to_numpy().astype(int)
data_np = data.to_numpy()
data_np = np.c_[np.ones(len(data_np)), data_np]
np.random.seed(42)
print(len(data_np))
rnd_indices = np.random.permutation(len(data_np))
target_np = target_np[rnd_indices]
data_np = data_np[rnd_indices]

150


In [472]:
target_np_transposed = target_np.T
data_np_transposed = data_np.T

In [473]:
data_np

array([[ 1.00000000e+00,  5.33620882e-01,  8.74617844e-04],
       [ 1.00000000e+00, -1.16580868e+00, -1.17985947e+00],
       [ 1.00000000e+00,  1.77986923e+00,  1.44399406e+00],
       [ 1.00000000e+00,  4.20325578e-01,  3.94452648e-01],
       [ 1.00000000e+00,  5.90268534e-01,  2.63259971e-01],
       [ 1.00000000e+00, -1.27910398e+00, -1.04866679e+00],
       [ 1.00000000e+00, -8.95032902e-02,  1.32067294e-01],
       [ 1.00000000e+00,  7.60211490e-01,  1.44399406e+00],
       [ 1.00000000e+00,  4.20325578e-01,  3.94452648e-01],
       [ 1.00000000e+00,  8.04396658e-02,  8.74617844e-04],
       [ 1.00000000e+00,  7.60211490e-01,  1.05041603e+00],
       [ 1.00000000e+00, -1.33575163e+00, -1.44224482e+00],
       [ 1.00000000e+00, -1.39239929e+00, -1.31105215e+00],
       [ 1.00000000e+00, -1.27910398e+00, -1.44224482e+00],
       [ 1.00000000e+00, -1.27910398e+00, -1.17985947e+00],
       [ 1.00000000e+00,  5.33620882e-01,  5.25645324e-01],
       [ 1.00000000e+00,  1.15674505e+00

In [474]:
split = 120
X_train, X_val, y_train, y_val = data_np_transposed[:, :split], data_np_transposed[:, split:], target_np_transposed[:, :split], target_np_transposed[:, split:],

In [475]:
target_np_transposed

array([[0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,

In [476]:
y_train.shape

(3, 120)

In [477]:
X_train.shape

(3, 120)

In [478]:

def softmax(data, weights):
    logits = (weights @ data)
    numerator = np.apply_along_axis((lambda x: np.exp(x)), 0, logits)
    denominator = numerator.sum(axis=0)
    return numerator/denominator

In [479]:
def cross_entropy(target, prediction):
    target=target
    loss = (-1/len(target))*(np.sum(target*np.log(prediction+1e-15)))
    return loss

In [480]:
def gradient(target, prediction, data):
    return (data @ np.subtract(prediction, target).T)/len(target)

In [481]:
def update_weights(weights, gradient, learning_rate):
    return (weights-((learning_rate*gradient).T))

In [482]:
sample_target = np.matrix([[0, 0, 1, 1], [1, 0, 0, 0], [0, 1, 0, 0]])
print(sample_target.shape)
sample_data = np.matrix([[1, 1, 1, 1], [3, 4, 5, 6], [2, 7, 3, 4]])#3 data points of 3 features each
print(sample_data.shape)

(3, 4)
(3, 4)


In [483]:
weights = np.random.rand(3, 3)
print(weights)
best_val_loss = float('inf')
best_weights = weights
epochs = 5000

data = X_train
target = y_train
val_data = X_val
val_target = y_val
# data = data_np_transposed
# target = target_np_transposed


for epoch in range(epochs):
    prediction = softmax(data, weights)
    loss = cross_entropy(target, prediction)
    gradients = gradient(target, prediction, data)
    new_weights = update_weights(weights, gradients, 0.05)
    weights = new_weights
    val_predict = softmax(val_data, weights)
    val_loss = cross_entropy(val_target, val_predict)
    if val_loss < best_val_loss:
         best_val_loss = val_loss
         best_weights = weights
    print(f"val_loss: {val_loss:.4f} \ntrain_loss: {loss:.4f}", flush=True)
    #best_weights = weights
    #print(loss, flush=True)

prediction = softmax(data, best_weights)
print(weights)

[[0.24929223 0.41038292 0.75555114]
 [0.22879817 0.07697991 0.28975145]
 [0.16122129 0.92969765 0.80812038]]
val_loss: 5.8905 
train_loss: 44.8970
val_loss: 5.0629 
train_loss: 20.5858
val_loss: 4.5089 
train_loss: 17.9146
val_loss: 4.1027 
train_loss: 16.0888
val_loss: 3.7903 
train_loss: 14.7566
val_loss: 3.5391 
train_loss: 13.7250
val_loss: 3.3303 
train_loss: 12.8883
val_loss: 3.1526 
train_loss: 12.1888
val_loss: 2.9988 
train_loss: 11.5916
val_loss: 2.8640 
train_loss: 11.0744
val_loss: 2.7446 
train_loss: 10.6212
val_loss: 2.6380 
train_loss: 10.2203
val_loss: 2.5420 
train_loss: 9.8630
val_loss: 2.4551 
train_loss: 9.5422
val_loss: 2.3761 
train_loss: 9.2526
val_loss: 2.3038 
train_loss: 8.9897
val_loss: 2.2374 
train_loss: 8.7498
val_loss: 2.1761 
train_loss: 8.5301
val_loss: 2.1194 
train_loss: 8.3280
val_loss: 2.0668 
train_loss: 8.1414
val_loss: 2.0178 
train_loss: 7.9685
val_loss: 1.9720 
train_loss: 7.8080
val_loss: 1.9292 
train_loss: 7.6583
val_loss: 1.8889 
train_loss

In [484]:
print(prediction[:, :4])

[[3.89451915e-04 9.92435491e-01 2.75044807e-14 1.30436643e-04]
 [9.81943915e-01 7.56450873e-03 7.74156852e-06 9.27559350e-01]
 [1.76666332e-02 4.72855927e-12 9.99992258e-01 7.23102135e-02]]


In [485]:
print(target[:, :4])

[[0 1 0 0]
 [1 0 0 1]
 [0 0 1 0]]
